development:
  host: localhost
  port: 5672
  db: 0
production:
  host: <%= ENV.fetch("RABBITMQ_HOST") { 'rabbitmq' } %>
  port: <%= ENV.fetch("RABBITMQ_PORT") { 5672 } %>
test:
  host: localhost
  port: 123
